###
GET http://localhost:4000/api/parametros/all
Content-Type:application/json
###

####
GET  http://localhost:4000/api/departamento/all
Content-Type:application/json

####
GET  http://localhost:4000/api/caso/all
Content-Type:application/json

####
GET  http://localhost:4000/api/tramite/all
Content-Type:application/json

####
GET  http://localhost:4000/api/caso/all
Content-Type:application/json

