###
GET http://localhost:4000/api/parametros/all
Content-Type:application/json
###

####
GET  http://localhost:4000/api/departamento/all
Content-Type:application/json

####
GET  http://localhost:4000/api/caso/all
Content-Type:application/json

####
GET  http://localhost:4000/api/tramite/all
Content-Type:application/json

####
GET  http://localhost:4000/api/caso/all
Content-Type:application/json

####
GET  http://localhost:4000/api/tramite/find

Content-Type:application/json
{
    id:"62ba4a803a066171dc18b63d"
}

####
GET  http://localhost:4000/api/documento/existe

Content-Type:application/json
    caso:"62ba4a803a066171dc18b63d",
    nombre:"cedula"